# on s'appie sur l'image de base alpine:3
FROM alpine:3

# on execute la commande mkdir dans l'image et on cree le ficher file.txt dans la foulée
    # la commande CMD sert à spéficier quel executable sera lancé au lancement du container
RUN mkdir /apps && \
    touch /apps/file.txt
